### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by moriarty** [ChrisQuignon/kivasim#12]
Hi, 

I've been sending reminders via GH issues that there will be presentations tomorrow. 
But I think that 10106275b316 is the presentation... So maybe you can ignore this. 

I've Bumped #2, #4 and #5. Just wanted to know what the progress is. 

Good Luck

**Comment by ChrisQuignon** [comment]
That indeed is the presentation.
Progress is fine, I'll close the issues after testing.
Thanks for the Bumps.
