### ISSUE TITLE
Issue running project

### ISSUE THREAD

**Issue by nao-de** [ChrisQuignon/kivasim#13]
Hi,

I'm trying to run the project on OS X. I'm getting "[java] Error: Could not find or load main class jade.Boot" from your build.xml when I try and build it. I have the latest version of Java. I'm wondering what sort of environment you used to run the project?

Thanks!

**Comment by moriarty** [comment]
I don't know this for sure, but I think it was likely Eclipse with the Jade plugin.

http://selab.fbk.eu/dnguyen/ejade/download.html

**Comment by moriarty** [comment]
From the build.xml:

```
<path id="kivasim.classpath">
    <pathelement location="bin"/>
    <pathelement location="../jade/lib/jade.jar"/>
</path>
```

Jade can be found here:

http://jade.tilab.com

**Comment by ChrisQuignon** [comment]
As @moriarty mentioned, I used Eclipse with the jade.jar.
You might want to start with a dummy project from a tutorial like https://saeedkhattak.wordpress.com/2012/03/07/jade-with-eclipse/ to get Jade running in Eclipse.

Kind regards, Chris
